<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <AssemblyName>HelloDI.Tests</AssemblyName>

    <RootNamespace>Ploeh.Samples.HelloDI.Tests</RootNamespace>

    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <DotNetCliToolReference Include="dotnet-xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelloDI.Console\HelloDI.Console.csproj" />
  </ItemGroup>

</Project>
