<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Ploeh.Samples.ProductManagement.Domain</AssemblyName>
    <RootNamespace>Ploeh.Samples.ProductManagement.Domain</RootNamespace>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

</Project>
